New rule
leoexcelsus/cella pull request #16
Opened 2020-10-03 14:39 UTC by vitorlsantana

Pessoal, iniciei a implementação da página para criação de nova norma. Após o cadastro, vinculei um link para o show da norma. Comecei com um simple form e não trabalhei nas funções para cadastro do polígono, pois acho que precisamos conversar mais sobre isso.

2020-10-03 19:49 UTC, leoexcelsus commented on app/views/devise/shared/_links.html.erb
> +  <% end %>
Vitor, depois que eu faço login, os botões "entrar" e "cadastrar" continuam aparecendo. Ademais, depois de logado, não achei botão de para 'sair'.
Há como você consertar isso antes do merge?

2020-10-03 19:51 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.input :jurisdiction, label: "Incluir polígono", collection: [['Federal', 'option_value_1', {"class" => "class_name_1"}], ['Estadual', 'option_value_2', {"class" => "class_name_2"}], ['Munic
Vitor, esse campo deveria ser de um tipo para subir um arquivo.

2020-10-03 19:55 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.input :issuer, label: "Emissor" %>
Será é possível incluir um recurso de 'autocomplete' ou de sugestões com base nos valores já disponíveis no banco de dados?
A intenção é minimizar o cadastramento de duas strings diferentes para a mesma Rule, como em "congresso nacional" e "Congresso nacional".

2020-10-03 19:59 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.input :jurisdiction, label: "Jurisdição", collection: [['Federal', 'option_value_1', {"class" => "class_name_1"}], ['Estadual', 'option_value_2', {"class" => "class_name_2"}], ['Municipal',
Dá pra colocar validação nos campos? Os 4 primeiros campos e o últimos são obrigatórios. Quanto aos outros, acho que precisamos discutir.... pelo menos uma das datas deveria ser preenchida pelo usuário. Atualmente, o usuário pode cadastrar uma nova norma sem nada informado. Minto, acho que os campos de datas  fazem a aplicação quebrar se estiverem vazios.

2020-10-03 20:01 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.button :button, "Cancelar", type: "reset", class: "btn-outline-secondary" %>
Acho que esse poderia uma botão vermelho.

2020-10-03 20:18 UTC, leoexcelsus requested changes

2020-10-03 20:18 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.button :submit, value: "Criar nova norma", class: "btn-ghost" %>
E se esse botão fosse verde? As cores desses botões  permitem ao usuário saber o que eles fazem sem nem ler o texto inserido neles...

2020-10-03 20:18 UTC, leoexcelsus commented on app/controllers/rules_controller.rb
> +
Falta associar a nova norma a um array de polígonos

2020-10-03 20:18 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.input :hyperlink, label: "Link da Norma" %>
Será que existe um filtro de links para não deixar os usuários colocarem links de páginas maliciosas ou indevidas?

2020-10-03 20:18 UTC, leoexcelsus commented on app/views/rules/_form.html.erb
> +    <%= f.input :category, label: "Categoria" %>
Sugiro colocar o 'label' aqui como 'tipo de norma', contendo ainda uma lista de valores possíveis como sugestão para minimizar strings diferentes que significam a mesma coisa.

2020-10-05 19:24 UTC, vitorlsantana commented on app/views/rules/_form.html.erb
> +    <%= f.button :button, "Cancelar", type: "reset", class: "btn-outline-secondary" %>
Implemented

2020-10-05 19:27 UTC, vitorlsantana commented on app/views/rules/_form.html.erb
> +    <%= f.input :category, label: "Categoria" %>
Done!

2020-10-06 01:03 UTC, vitorlsantana commented on app/views/devise/shared/_links.html.erb
> +  <% end %>
Done!

2020-10-06 01:03 UTC, vitorlsantana commented on app/views/rules/_form.html.erb
> +    <%= f.input :jurisdiction, label: "Incluir polígono", collection: [['Federal', 'option_value_1', {"class" => "class_name_1"}], ['Estadual', 'option_value_2', {"class" => "class_name_2"}], ['Munic
Leandro, implementei o campo para fazer o upload do arquivo, mas preciso ajustar o controller de rules para salvar a rule com os campos industry e polygon

2020-10-06 01:04 UTC, vitorlsantana commented on app/views/rules/_form.html.erb
> +    <%= f.input :issuer, label: "Emissor" %>
Para isso, preciso ter uma referência do autocomplete, uma API por exemplo. Precisamos conversar melhor sobre a viabilidade disso nesse momento.

2020-10-06 15:34 UTC, merged